version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sportbuddy-webapp
    container_name: sportbuddy-webapp
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Database=SportBuddy;Username=postgres;Password=postgres;
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: sportbuddy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
