@url = http://localhost:5000
@matchId = 00000000-0000-0000-0000-000000000001
@groupId = 00000000-0000-0000-0000-000000000001
@userId = 00000000-0000-0000-0000-000000000001
@adminId = 00000000-0000-0000-0000-000000000001
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/users

###
POST {{url}}/users
Content-Type: application/json

{
    "email": "user@test.com",
    "username": "username",
    "password": "password123!",
    "fullName": "Marek Adamski",
    "role": "user"
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "password123!"
}

###
GET {{url}}/users/{{userId}}
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users/me
Authorization: Bearer {{accessToken}}



###
GET {{url}}/groups

###
GET {{url}}/groups/{{groupId}}

###
POST {{url}}/groups
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Marek Adamski group",
    "description": "super group",
    "groupType": 0
}

### 
GET {{url}}/groups/{{groupId}}/usersToInvite
Authorization: Bearer {{accessToken}}

### 
GET {{url}}/groups/{{groupId}}/users

###
POST {{url}}/groups/{{groupId}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userIds": [
        "f60f6915-0f47-4bea-b616-81dd1a5e9eb8"
    ]
}

###
DELETE {{url}}/groups/{{groupId}}/leave
Authorization: Bearer {{accessToken}}

###
POST {{url}}/groups/{{groupId}}/matches
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "match3",
    "discipline": 0,
    "location": "Warsaw",
    "start": "2020-01-01T00:10:00+00:00",
    "end": "2020-01-01T00:11:00+00:00",
    "charge": 10.0,
    "limit": 10
}



###
GET {{url}}/matches

###
GET {{url}}/matches/{{matchId}}

###
POST {{url}}/matches
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000001",
    "name": "match1",
    "date": "2020-01-01T00:00:00+00:00"
}

###
POST {{url}}/matches/{{matchId}}/register
Authorization: Bearer {{accessToken}}

###
DELETE {{url}}/matches/{{matchId}}/leave
Authorization: Bearer {{accessToken}}

### 
GET {{url}}/matches/{{matchId}}/members
